import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import { useEffect } from 'react';
import RootLayout from '../path/to/RootLayout'; // Update the path
import { TUPCIDProvider } from '../path/to/TUPCIDContext'; // Update the path

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'AUTO CHECKER',
  description: 'Generated by create next app',
}

function MyApp({ Component, pageProps }) {
  useEffect(() => {
    import('bootstrap/dist/js/bootstrap');
  }, []);

  return (
    <TUPCIDProvider>
      <RootLayout>
        {/* Wrap your entire app content with the RootLayout component */}
        <Component {...pageProps} />
      </RootLayout>
    </TUPCIDProvider>
  );
}

export default MyApp;
